### PR TITLE
Add Makefile

### PR DESCRIPTION
**Pull request by SuperSandro2000**

### CODE REVIEW

**Comment by lyknode** [comment]
Hi @SuperSandro2000,

I was going to take care of that but you did it first ^^. Allow me to comment on some suggestions.

- Could you include support for [`$(DESTDIR)`](https://www.gnu.org/prep/standards/html_node/DESTDIR.html)? Those are used by packaging tools, allowing files to be installed in a relative path from PREFIX.
Usually in makefiles, you would find:
```make
PREFIX ?= /usr/local
mandir := $(DESTDIR)$(PREFIX)/man
man1dir := $(mandir)/man1
bindir := $(DESTDIR)$(PREFIX)/bin
```
- Could you not include `test` and `install` in the `all` target? By convention, `make` must only build and not require privileges (which `install` might depending on `DESTDIR` and `PREFIX`), ideally users do `make && make test && sudo make install`.
- Could you explicitly install `mgitstatus` with a 755 mode?
- Could you not add `--no-print-directory`, this is GNU make specific and users and tools might want/expect path to be printed.

The next two suggestions are just my preference so fell free to ignore those totally:
- You are not using any syntax specific to bash, so you could replace `SHELL` by `/bin/sh` to allow building on a wider set of systems.
- You don't need `DEFAULT_GOAL` if all is your first target in the makefile, which it is by convention.

**Comment by lyknode** [comment]
Also, you didn't remove `build.sla` and `install.sh`.

**Comment by SuperSandro2000** [comment]
> Could you not add --no-print-directory, this is GNU make specific and users and tools might want/expect path to be printed.
> You are not using any syntax specific to bash, so you could replace SHELL by /bin/sh to allow building on a wider set of systems.

I just copied that from my default Makefile.

Changed all the things you requested.

**Comment by lyknode** [comment]
Thanks for the quick fix!

You are missing a `.PHONY` tag for the `install` target and then it should be good.

**Comment by SuperSandro2000** [comment]
@lyknode Added that

**Comment by lyknode** [comment]
Ah, we forgot the `clean` rule. Could you make it remove the generated manpage?

**Comment by SuperSandro2000** [comment]
The manpage is currently tracked in git and removing it would cause changes to the cwd.

When the manpage is converted to troff we don't need the generation or clean.

**Comment by lyknode** [comment]
As per last comment on #38, the manpage would be removed and the markdown kept. But you are right, the `clean` target doesn't need to be added right now. It can be done afterward as the file is removed from the repo.

**Pull request merged**
